import sys
sys.path.insert(0, "/serialCommands")

from serialCommands import *
from serial import Serial
import time

legs = Serial('/dev/ttyACM0', 1000000)
torso = Serial('/dev/ttyACM1', 1000000)

idsLegs = [11, 12, 13, 14, 15, 21, 22, 23, 24, 25]
idsTorso = [31, 32, 34, 35, 36, 37, 41, 42, 43, 44, 51, 52, 53, 54]

startTime = 0.7
executionTime = 2
bufferTime = 0.01

defineAngleLimitsFromJSON(legs, torso)
print('Definido limites de angulos dos motores!')

setTorques(legs, idsLegs, 1)
time.sleep(startTime)
setTorques(torso, idsTorso, 1)
time.sleep(startTime)

goToPosition(legs, 15, 1808)
print('Colocando o pe esquerdo em posicao!')
time.sleep(startTime)
goToPosition(legs, 25, 1993)
print('Colocando o pe direito em posicao!')
time.sleep(startTime)
goToPosition(legs, 14, 1941)
print('Colocando o joelho esquerdo em posicao!')
time.sleep(startTime)
goToPosition(legs, 24, 1950)
print('Colocando o joelho direito em posicao!')
time.sleep(startTime)
goToPosition(legs, 13, 2111)
print('Colocando a coxa esquerda em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(legs, 23, 2193)
print('Colocando a coxa direita em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(legs, 12, 2118)
print('Colocando a coxa esquerda em relacao ao Z em posicao!')
time.sleep(startTime)
goToPosition(legs, 22, 2117)
print('Colocando a coxa direita em relacao ao Z em posicao!')
time.sleep(startTime)
goToPosition(legs, 11, 2100)
print('Colocando a coxa esquerda em relacao ao X em posicao!')
time.sleep(startTime)
goToPosition(legs, 21, 1840)
print('Colocando a coxa direita em relacao ao X em posicao!')
time.sleep(startTime)
goToPosition(torso, 31, 1943)
print('Colocando o abdomen em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(torso, 32, 2093)
print('Colocando o abdomen em relacao ao X em posicao!')
time.sleep(startTime)
# goToPosition(torso, 33, 0000)
# print('Colocando o abdomen em relacao ao Z em posicao!')
# time.sleep(startTime)
goToPosition(torso, 34, 2140)
print('Colocando o torax em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(torso, 35, 2098)
print('Colocando o torax em relacao ao X em posicao!')
time.sleep(startTime)
goToPosition(torso, 36, 503)
print('Colocando a cabeca em relacao ao Z em posicao!')
time.sleep(startTime)
goToPosition(torso, 41, 3088)
print('Colocando o ombro esquerdo em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(torso, 51, 1008)
print('Colocando o ombro direito em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(torso, 37, 409)
print('Colocando a cabeca em relacao ao Y em posicao!')
time.sleep(startTime)
goToPosition(torso, 42, 3225)
print('Colocando o ombro esquerdo em relacao ao X em posicao!')
time.sleep(startTime)
goToPosition(torso, 52, 1034)
print('Colocando o ombro direito em relacao ao X em posicao!')
time.sleep(startTime)
goToPosition(torso, 43, 1764)
print('Colocando o braco esquerdo em posicao!')
time.sleep(startTime)
goToPosition(torso, 53, 2045)
print('Colocando o braco direito em posicao!')
time.sleep(startTime)
goToPosition(torso, 44, 1227)
print('Colocando o antebraco esquerdo em posicao!')
time.sleep(startTime)
goToPosition(torso, 54, 2192)
print('Colocando o antebraco direito em posicao!')
time.sleep(startTime)

setTorquesPower(torso, [34, 35, 36, 37, 41, 42, 43, 44, 51, 52, 53, 54], 512)
print('Definindo velocidade do torso MX-28AT!')
time.sleep(startTime)

setTorquePower(torso, [31, 32], 400)
print('Definindo velocidade do torso MX-64AT!')
time.sleep(startTime)

print('\n\n\n\n\n\n' + '-'*50)
print('Executando programacao da Macarena em...')
time.sleep(1.5)
print('3...')
time.sleep(1.5)
print('2...')
time.sleep(1.5)
print('1...')
time.sleep(1.5)
print('0\n\n\n')

# Posicao 01
goToPosition(torso, 51, 2048)
time.sleep(bufferTime)
goToPosition(torso, 53, 1038)
time.sleep(bufferTime)
goToPosition(torso, 54, 2060)
time.sleep(bufferTime)
print('Ativando posicao 1!')
time.sleep(executionTime)

# Posicao 02
goToPosition(torso, 31, 2062)
time.sleep(bufferTime)
goToPosition(torso, 35, 2069)
time.sleep(bufferTime)
goToPosition(torso, 41, 2018)
time.sleep(bufferTime)
goToPosition(torso, 43, 2839)
time.sleep(bufferTime)
goToPosition(torso, 44, 1063)
time.sleep(bufferTime)
print('Ativando posicao 2!')
time.sleep(executionTime)

# Posicao 03
goToPosition(torso, 53, 3018)
time.sleep(bufferTime)
print('Ativando posicao 3!')
time.sleep(executionTime)

# Posicao 04
goToPosition(torso, 43, 901)
time.sleep(bufferTime)
print('Ativando posicao 4!')
time.sleep(executionTime)

# Posicao 05
goToPosition(torso, 42, 3120)
time.sleep(bufferTime)
goToPosition(torso, 53, 1084)
time.sleep(bufferTime)
goToPosition(torso, 51, 1847)
time.sleep(bufferTime)
goToPosition(torso, 54, 3116)
time.sleep(bufferTime)
print('Ativando posicao 5!')
time.sleep(executionTime)

# Posicao 06
goToPosition(torso, 41, 1929)
time.sleep(bufferTime)
goToPosition(torso, 42, 3222)
time.sleep(bufferTime)
goToPosition(torso, 43, 2880)
time.sleep(bufferTime)
goToPosition(torso, 44, 2066)
time.sleep(bufferTime)
print('Ativando posicao 6!')
time.sleep(executionTime)

torso.close()
legs.close()
